# Generated by Django 4.1.7 on 2023-04-07 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("endpoint_token", models.CharField(max_length=255)),
                ("contador", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "empresas",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "planes",
            },
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("billing_state", models.CharField(max_length=2)),
                ("user_agent", models.CharField(max_length=255)),
                ("billing_postal", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("EVENT_TIMESTAMP", models.DateTimeField()),
                ("billing_address", models.CharField(max_length=255)),
                ("EVENT_LABEL", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kaax_app.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "transacciones",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kaax_app.plan"
            ),
        ),
    ]
