# Generated by Django 4.1.7 on 2023-04-07 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kaax_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empresa",
            old_name="plan_id",
            new_name="plan",
        ),
        migrations.RenameField(
            model_name="transaccion",
            old_name="empresa_id",
            new_name="empresa",
        ),
    ]
