# Generated by Django 4.1.7 on 2023-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaax_app", "0003_rename_transaccion_transacciones_prueba_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacciones_prueba",
            name="EVENT_TIMESTAMP",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transacciones_prueba",
            name="billing_state",
            field=models.CharField(max_length=255),
        ),
    ]
