# Generated by Django 4.1.7 on 2023-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaax_app", "0004_alter_transacciones_prueba_event_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacciones_prueba",
            name="billing_postal",
            field=models.CharField(max_length=255),
        ),
    ]
