# Generated by Django 4.1.7 on 2023-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaax_app", "0005_alter_transacciones_prueba_billing_postal"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacciones_prueba",
            name="archivo",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
