# Generated by Django 4.1.7 on 2023-04-12 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("kaax_app", "0006_transacciones_prueba_archivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrenamientos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precision", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "entrenamientos",
            },
        ),
    ]
